version: '3.1'

services:
  db:
    image: postgres:10.15-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      TZ: Asia/Taipei
      POSTGRES_PASSWORD: admin
#      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
#      - ./pgdata:/var/lib/postgresql/data
#      - ./postgres_data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 7890:8080

volumes:
  pgdata:

networks:
  default:
    external:
      name: svc-overlay-network
